import { HytaleNode } from "@/types/editor";

export const generateJava = (
    nodes: HytaleNode[], 
    className = "MyGeneratedGui", 
    uiFilePath = "Pages/MyMod_GUI.ui",
    packageName = "com.example.mod"
) => {

    // 1. FILTRAR ELEMENTOS DE INTERÉS
    const inputs = nodes.filter(n => n.type.includes("TextField") && n.properties.binding);
    const textElements = nodes.filter(n => 
        n.name && n.properties.text && !n.type.includes("TextField")
    );
    const clickableElements = nodes.filter(n => 
        n.name && (n.type.includes("Button") || n.type.includes("Clickable"))
    );

    // 2. GENERAR CÓDIGO INTERNO
    const bindingFields = inputs.map(n => 
        `        public String ${n.properties.binding}; // Linked to #${n.name}`
    ).join("\n");

    // -> Generar lógica de Build (setText y bindClick)
    let buildLogic = `        // Cargar el archivo UI generado\n        uiCommandBuilder.append("${uiFilePath}");\n\n`;

    if (textElements.length > 0) {
        buildLogic += `        // --- Textos Iniciales ---\n`;
        textElements.forEach(n => {
            // Escapar comillas dobles en el texto Java
            const safeText = n.properties.text?.replace(/"/g, '\\"');
            buildLogic += `        uiCommandBuilder.setText("#${n.name}", "${safeText}");\n`;
        });
        buildLogic += `\n`;
    }

    if (clickableElements.length > 0) {
        buildLogic += `        // --- Eventos de Click ---\n`;
        clickableElements.forEach(n => {
            // Usamos la propiedad 'binding' como nombre de acción, o un fallback 'action_ID'
            const actionName = n.properties.binding || `action_${n.name}`;
            buildLogic += `        uiEventBuilder.bindClick("#${n.name}", "${actionName}");\n`;
        });
    }

    // -> Generar lógica de Eventos (Handle Data)
    let eventLogic = "";
    clickableElements.forEach((n, index) => {
        const actionName = n.properties.binding || `action_${n.name}`;
        const prefix = index === 0 ? "if" : "else if";
        
        eventLogic += `        ${prefix} ("${actionName}".equals(data.action)) {\n`;
        eventLogic += `            this.playerRef.sendMessage(Message.raw("Click en ${n.name} detected."));\n`;
        eventLogic += `            // TODO: Add logic for ${n.name}\n`;
        eventLogic += `        }\n`;
    });

    // 3. PLANTILLA FINAL
    return `package ${packageName};

    import com.hypixel.hytale.codec.Codec;
    import com.hypixel.hytale.codec.KeyedCodec;
    import com.hypixel.hytale.codec.builder.BuilderCodec;
    import com.hypixel.hytale.component.Ref;
    import com.hypixel.hytale.component.Store;
    import com.hypixel.hytale.protocol.packets.interface_.CustomPageLifetime;
    import com.hypixel.hytale.server.core.Message;
    import com.hypixel.hytale.server.core.entity.entities.player.pages.InteractiveCustomUIPage;
    import com.hypixel.hytale.server.core.ui.builder.UICommandBuilder;
    import com.hypixel.hytale.server.core.ui.builder.UIEventBuilder;
    import com.hypixel.hytale.server.core.universe.PlayerRef;
    import com.hypixel.hytale.server.core.universe.world.storage.EntityStore;
    import javax.annotation.Nonnull;

    /**
     * Generated by Hyve UI Editor
     * Logic class for: ${uiFilePath}
     */
    public class ${className} extends InteractiveCustomUIPage<${className}.BindingData> {

        public ${className}(@Nonnull PlayerRef playerRef, @Nonnull CustomPageLifetime lifetime) {
            super(playerRef, lifetime, BindingData.CODEC);
        }

        // --- DATA CLASS (Inputs & Bindings) ---
        public static class BindingData {
            // Campos obligatorios para detectar clicks
            public String action; 
            
    ${bindingFields}

            public static final BuilderCodec<BindingData> CODEC = BuilderCodec.builder(BindingData.class, BindingData::new)
                    .field("action", KeyedCodec.STRING, (d) -> d.action, (d, v) -> d.action = v)
    ${inputs.map(n => `                .field("${n.properties.binding}", KeyedCodec.STRING, (d) -> d.${n.properties.binding}, (d, v) -> d.${n.properties.binding} = v)`).join("\n")}
                    .build();
        }
        
        // --- BUILD (Initial State) ---
        @Override
        public void build(@Nonnull Ref<EntityStore> ref, @Nonnull UICommandBuilder uiCommandBuilder, @Nonnull UIEventBuilder uiEventBuilder, @Nonnull Store<EntityStore> store) {
    ${buildLogic}
        }

        // --- EVENTS (Interaction) ---
        @Override
        public void handleDataEvent(@Nonnull Ref<EntityStore> ref, @Nonnull Store<EntityStore> store, @Nonnull BindingData data) {
            super.handleDataEvent(ref, store, data);
            
            if (data.action == null) return;

    ${eventLogic}
        }
    }`;
};